### ISSUE TITLE
Guide references old io.micronaut:micronaut-discovery-client artifact

### ISSUE THREAD

**Issue by debuglevel** [micronaut-projects/micronaut-discovery-client#310]
### Expected Behavior

References "io.micronaut.discovery:micronaut-discovery-client"

### Actual Behaviour

References "io.micronaut:micronaut-discovery-client"

### Steps To Reproduce

Unfortunately I don't know how adoc resolves the `dependency:micronaut-discovery-client` thingy. Otherwise I'd create a PR :)

### Version

3.0.0

**Comment by ilopmar** [comment]
This is the file to modify https://github.com/micronaut-projects/micronaut-discovery-client/blob/master/src/main/docs/guide/introduction.adoc

Look for `dependency:micronaut-discovery-client[]`. It should be `dependency:micronaut-discovery-client[groupId=io.micronaut.discovery]`

After the change, run `./gradlew docs` to generate the docs locally and verify that the correct groupId is there.

Thanks for the future PR :smiley:
